"use client";
import {useEffect,useMemo,useState} from "react";

type Resident={id:string;firstName:string;lastName:string;referenceId?:string};
type Appointment={id:string;residentId:string;residentName:string;providerName:string;appointmentType:string;appointmentDate:string;startTime:string;endTime:string;location:string;reason:string;status:string;notes:string;createdAt:string};
const statuses=["Scheduled","Confirmed","Completed","Cancelled","No Show"];
const types=["Primary Care Physician","Psychiatric Provider","Specialist Visit","Dental","Emergency Room","Urgent Care","Therapy","Lab","Other"];
const blank={residentId:"",providerName:"",appointmentType:"",appointmentDate:"",startTime:"",endTime:"",location:"",reason:"",status:"Scheduled",notes:""};
export default function AppointmentManager({canManage,initialResidentId=""}:{canManage:boolean;initialResidentId?:string}){ const [residents,setResidents]=useState<Resident[]>([]); const [rows,setRows]=useState<Appointment[]>([]); const [form,setForm]=useState<any>(blank); const [edit,setEdit]=useState<Appointment|null>(null); const [open,setOpen]=useState(false); const [q,setQ]=useState(""); const [status,setStatus]=useState("All"); const [msg,setMsg]=useState("");
 async function load(){const [rr,ar]=await Promise.all([fetch('/api/residents'),fetch('/api/appointments')]);const [r,a]=await Promise.all([rr.json(),ar.json()]);setResidents(Array.isArray(r)?r:[]);setRows(Array.isArray(a)?a:[])}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(initialResidentId&&canManage){setForm({...blank,residentId:initialResidentId});setEdit(null);setOpen(true)}},[initialResidentId,canManage]);
 const filtered=useMemo(()=>rows.filter(x=>{const hay=`${x.residentName} ${x.providerName} ${x.appointmentType} ${x.location} ${x.status}`.toLowerCase();return hay.includes(q.toLowerCase())&&(status==="All"||x.status===status)}),[rows,q,status]);
 function startCreate(){setEdit(null);setForm(blank);setOpen(true);setMsg("")}
 function startEdit(a:Appointment){setEdit(a);setForm({residentId:a.residentId,providerName:a.providerName||"",appointmentType:a.appointmentType||"",appointmentDate:a.appointmentDate||"",startTime:a.startTime||"",endTime:a.endTime||"",location:a.location||"",reason:a.reason||"",status:a.status||"Scheduled",notes:a.notes||""});setOpen(true);setMsg("")}
 async function save(e:any){e.preventDefault();setMsg("");const url=edit?`/api/appointments/${edit.id}`:'/api/appointments';const method=edit?'PUT':'POST';const r=await fetch(url,{method,headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok){setMsg(j.error||"Unable to save appointment.");return}setOpen(false);setEdit(null);setForm(blank);await load()}
 async function del(id:string){if(!confirm("Delete this appointment?"))return;const r=await fetch(`/api/appointments/${id}`,{method:'DELETE'});if(!r.ok){const j=await r.json();alert(j.error||"Unable to delete appointment.");return}load()}
 return <><div className="pagehead"><div><h2>Appointments</h2><div className="muted">Book, reschedule and track resident appointments.</div></div>{canManage&&<button className="btn btn-primary" onClick={startCreate}>+ Book Appointment</button>}</div>
 <div className="card section"><div className="toolbar"><input className="input" style={{minWidth:320}} placeholder="Search resident, provider, type or location..." value={q} onChange={e=>setQ(e.target.value)}/><div className="actions"><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><span className="muted">{filtered.length} appointments</span></div></div></div>
 <div className="card tablewrap"><table className="table"><thead><tr><th>Date / Time</th><th>Resident</th><th>Type</th><th>Provider</th><th>Location</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(a=><tr key={a.id}><td><b>{a.appointmentDate||'—'}</b><div className="muted">{a.startTime||'—'}{a.endTime?` – ${a.endTime}`:""}</div></td><td><b>{a.residentName}</b></td><td>{a.appointmentType||'—'}</td><td>{a.providerName||'—'}</td><td>{a.location||'—'}</td><td><span className={`badge ${a.status==='Completed'?'green':a.status==='Cancelled'||a.status==='No Show'?'gray':'blue'}`}>{a.status}</span></td><td><div className="actions">{canManage&&<><button className="btn btn-ghost compactBtn" onClick={()=>startEdit(a)}>Edit</button><button className="btn btn-danger compactBtn" onClick={()=>del(a.id)}>Delete</button></>}</div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No appointments found.</div>}</div>
 {open&&<div className="modalOverlay"><form className="card section modalCard" onSubmit={save}><div className="pagehead"><div><h2>{edit?'Edit Appointment':'Book Appointment'}</h2><div className="muted">Resident appointment details and tracking status.</div></div><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Close</button></div><div className="formgrid">
 <div className="field"><label>Resident *</label><select className="select" required value={form.residentId} onChange={e=>setForm({...form,residentId:e.target.value})}><option value="">Select Resident</option>{residents.map(r=><option key={r.id} value={r.id}>{r.firstName} {r.lastName} · {r.referenceId||''}</option>)}</select></div>
 <div className="field"><label>Appointment Type *</label><select className="select" required value={form.appointmentType} onChange={e=>setForm({...form,appointmentType:e.target.value})}><option value="">Select Type</option>{types.map(t=><option key={t}>{t}</option>)}</select></div>
 <div className="field"><label>Date *</label><input className="input" type="date" required value={form.appointmentDate} onChange={e=>setForm({...form,appointmentDate:e.target.value})}/></div>
 <div className="field"><label>Status</label><select className="select" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="field"><label>Start Time *</label><input className="input" type="time" required value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></div>
 <div className="field"><label>End Time</label><input className="input" type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></div>
 <div className="field"><label>Provider</label><input className="input" value={form.providerName} onChange={e=>setForm({...form,providerName:e.target.value})}/></div>
 <div className="field"><label>Location / Address</label><input className="input" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div>
 <div className="field full"><label>Reason for Visit</label><textarea className="textarea" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></div>
 <div className="field full"><label>Notes</label><textarea className="textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div>
 </div>{msg&&<div className="err" style={{marginTop:12}}>{msg}</div>}<div className="actions" style={{justifyContent:'flex-end',marginTop:18}}><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary">{edit?'Update Appointment':'Book Appointment'}</button></div></form></div>}
 </>
}
