"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import type {EmployeeModule} from "@/lib/employee-modules";

export default function EmployeeRecordManager({module,canManage}:{module:EmployeeModule;canManage:boolean}){
 const sb=useMemo(()=>createClient(),[]); const [data,setData]=useState<Record<string,any>>({}); const [rows,setRows]=useState<any[]>([]); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState(""); const [editId,setEditId]=useState<string|null>(null); const [viewRow,setViewRow]=useState<any|null>(null); const [profiles,setProfiles]=useState<any[]>([]); const [employeeId,setEmployeeId]=useState(""); const [selfId,setSelfId]=useState("");
 const load=async()=>{const {data:{user}}=await sb.auth.getUser();setSelfId(user?.id||""); if(!employeeId)setEmployeeId(user?.id||""); let q=sb.from("employee_records").select("*").eq("module",module.slug).order("created_at",{ascending:false});if(!canManage&&user?.id)q=q.eq("employee_id",user.id);const {data:r}=await q;setRows(r||[]);if(canManage){const {data:p}=await sb.from("profiles").select("id,full_name,role,active").eq("active",true).order("full_name");setProfiles(p||[])}};
 useEffect(()=>{load()},[module.slug]);
 const set=(k:string,v:any)=>setData(x=>({...x,[k]:v}));
 const upload=async(k:string,file:File)=>{const {data:{user}}=await sb.auth.getUser(); const path=`${user?.id||"unknown"}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`; const {error}=await sb.storage.from("employee-documents").upload(path,file); if(error){setMsg(error.message);return} set(k,{name:file.name,path})};
 const save=async(status:"draft"|"submitted")=>{for(const f of module.fields)if(f.required&&!data[f.key]){setMsg(`${f.label} is required.`);return} setSaving(true);setMsg("");const {data:{user}}=await sb.auth.getUser();const target=canManage?(employeeId||user?.id):user?.id;if(!target){setMsg("Select an employee.");setSaving(false);return}const payload={employee_id:target,module:module.slug,title:module.title,status,data,created_by:user?.id||null,updated_at:new Date().toISOString()};const result=editId?await sb.from("employee_records").update(payload).eq("id",editId):await sb.from("employee_records").insert(payload);setSaving(false);if(result.error){setMsg(result.error.message);return}setData({});setEditId(null);await load();setMsg(editId?"Record updated.":status==="draft"?"Draft saved.":"Record submitted.")};
 const del=async(id:string)=>{if(!confirm("Delete this record?"))return;const {error}=await sb.from("employee_records").delete().eq("id",id);if(error){alert(error.message);return}load()};
 const edit=(row:any)=>{setEditId(row.id);setEmployeeId(row.employee_id||selfId);setData(row.data||{});window.scrollTo({top:0,behavior:"smooth"})};
 return <div className="emp-page"><div className="emp-head"><Link href="/employee">← Back</Link><div><h1>{module.title}</h1><p>{module.description}</p></div><span/></div>
 <div className="emp-card"><div className="pagehead"><div><h2>{editId?"Edit Record":"New Record"}</h2><div className="muted">{editId?"Update the saved employee record.":"Complete the form and save as draft or submit."}</div></div>{editId&&<button className="btn btn-ghost" onClick={()=>{setEditId(null);setData({})}}>Cancel Edit</button>}</div>{canManage&&<label className="emp-span-2"><b>Employee / Staff Member *</b><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Select employee...</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name||p.id} — {p.role}</option>)}</select></label>}
 <div className="emp-form-grid">{module.fields.map(f=><label key={f.key} className={f.type==="textarea"?"emp-span-2":""}><b>{f.label}{f.required?" *":""}</b>{f.type==="textarea"?<textarea value={data[f.key]||""} onChange={e=>set(f.key,e.target.value)}/>:f.type==="select"?<select value={data[f.key]||""} onChange={e=>set(f.key,e.target.value)}><option value="">Select...</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:f.type==="checkbox"?<div className="emp-check"><input type="checkbox" checked={!!data[f.key]} onChange={e=>set(f.key,e.target.checked)}/> Yes, I acknowledge / consent</div>:f.type==="file"?<div>{data[f.key]?.name&&<small className="muted">Current: {data[f.key].name}</small>}<input type="file" onChange={e=>e.target.files?.[0]&&upload(f.key,e.target.files[0])}/></div>:<input type={f.type||"text"} placeholder={f.placeholder} value={data[f.key]||""} onChange={e=>set(f.key,e.target.value)}/>}</label>)}</div>{msg&&<div className="emp-msg">{msg}</div>}<div className="emp-actions"><button className="emp-outline" onClick={()=>save("draft")} disabled={saving}>{editId?"Update Draft":"Save as Draft"}</button><button className="emp-primary" onClick={()=>save("submitted")} disabled={saving}>{editId?"UPDATE":"SUBMIT"}</button></div></div>
 <div className="emp-card"><h2>Records</h2>{rows.length===0?<div className="emp-empty">No Results Found</div>:<div className="emp-table-wrap"><table className="emp-table"><thead><tr><th>Date</th>{canManage&&<th>Employee</th>}<th>Status</th><th>Summary</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{new Date(row.created_at).toLocaleDateString()}</td>{canManage&&<td>{profiles.find(p=>p.id===row.employee_id)?.full_name||row.employee_id?.slice(0,8)||"—"}</td>}<td><span className={`emp-badge ${row.status}`}>{row.status}</span></td><td>{Object.entries(row.data||{}).filter(([,v])=>typeof v==="string"&&v).slice(0,3).map(([k,v])=>`${k.replaceAll("_"," ")}: ${v}`).join(" · ")||module.title}</td><td><div className="actions"><button className="btn btn-ghost compactBtn" onClick={()=>setViewRow(row)}>View</button>{canManage||row.employee_id===selfId?<button className="btn btn-ghost compactBtn" onClick={()=>edit(row)}>Edit</button>:null}{canManage&&<button className="emp-danger" onClick={()=>del(row.id)}>Delete</button>}</div></td></tr>)}</tbody></table></div>}</div>
 {viewRow&&<div className="modalOverlay"><div className="card section modalCard"><div className="pagehead"><h2>{module.title}</h2><button className="btn btn-ghost" onClick={()=>setViewRow(null)}>Close</button></div><div className="recordDetailGrid">{Object.entries(viewRow.data||{}).map(([k,v])=><div key={k}><small>{k.replaceAll('_',' ')}</small><div>{typeof v==='object'?JSON.stringify(v):String(v||'—')}</div></div>)}</div></div></div>}
 </div>
}
