"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@/lib/supabase/client";
import type {EmployeeModule} from "@/lib/employee-modules";
export default function EmployeeRecordManager({module}:{module:EmployeeModule}){
 const sb=useMemo(()=>createClient(),[]); const [data,setData]=useState<Record<string,any>>({}); const [rows,setRows]=useState<any[]>([]); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState("");
 const load=async()=>{const {data:r}=await sb.from("employee_records").select("*").eq("module",module.slug).order("created_at",{ascending:false});setRows(r||[])};
 useEffect(()=>{load()},[module.slug]);
 const set=(k:string,v:any)=>setData(x=>({...x,[k]:v}));
 const upload=async(k:string,file:File)=>{const {data:{user}}=await sb.auth.getUser(); const path=`${user?.id||"unknown"}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`; const {error}=await sb.storage.from("employee-documents").upload(path,file); if(error){setMsg(error.message);return} set(k,{name:file.name,path})};
 const save=async(status:"draft"|"submitted")=>{for(const f of module.fields)if(f.required&&!data[f.key]){setMsg(`${f.label} is required.`);return} setSaving(true);setMsg("");const {data:{user}}=await sb.auth.getUser();const {error}=await sb.from("employee_records").insert({employee_id:user?.id||null,module:module.slug,title:module.title,status,data,created_by:user?.id||null});setSaving(false);if(error){setMsg(error.message);return}setData({});await load();setMsg(status==="draft"?"Draft saved.":"Record submitted.")};
 const del=async(id:string)=>{if(!confirm("Delete this record?"))return;await sb.from("employee_records").delete().eq("id",id);load()};
 return <div className="emp-page"><div className="emp-head"><Link href="/employee">← Back</Link><div><h1>{module.title}</h1><p>{module.description}</p></div><span/></div><div className="emp-card"><div className="emp-form-grid">{module.fields.map(f=><label key={f.key} className={f.type==="textarea"?"emp-span-2":""}><b>{f.label}{f.required?" *":""}</b>{f.type==="textarea"?<textarea value={data[f.key]||""} onChange={e=>set(f.key,e.target.value)}/>:f.type==="select"?<select value={data[f.key]||""} onChange={e=>set(f.key,e.target.value)}><option value="">Select...</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:f.type==="checkbox"?<div className="emp-check"><input type="checkbox" checked={!!data[f.key]} onChange={e=>set(f.key,e.target.checked)}/> Yes, I acknowledge / consent</div>:f.type==="file"?<input type="file" onChange={e=>e.target.files?.[0]&&upload(f.key,e.target.files[0])}/>:<input type={f.type||"text"} placeholder={f.placeholder} value={data[f.key]||""} onChange={e=>set(f.key,e.target.value)}/>}</label>)}</div>{msg&&<div className="emp-msg">{msg}</div>}<div className="emp-actions"><button className="emp-outline" onClick={()=>save("draft")} disabled={saving}>Save as Draft</button><button className="emp-primary" onClick={()=>save("submitted")} disabled={saving}>SUBMIT</button></div></div><div className="emp-card"><h2>Records</h2>{rows.length===0?<div className="emp-empty">No Results Found</div>:<div className="emp-table-wrap"><table className="emp-table"><thead><tr><th>Date</th><th>Status</th><th>Summary</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{new Date(row.created_at).toLocaleDateString()}</td><td><span className={`emp-badge ${row.status}`}>{row.status}</span></td><td>{Object.entries(row.data||{}).filter(([,v])=>typeof v==="string"&&v).slice(0,3).map(([k,v])=>`${k.replaceAll("_"," ")}: ${v}`).join(" · ")||module.title}</td><td><button className="emp-danger" onClick={()=>del(row.id)}>Delete</button></td></tr>)}</tbody></table></div>}</div></div>
}