"use client";
import {useEffect,useMemo,useState} from "react";

type MarEdit={med:any;date:string;time:string;record?:any}|null;
const CODES=['GIVEN','H','HP','RM','HO','UN','D'];
export default function MARManager({canAdminister=true}:{canAdminister?:boolean}){
 const [residents,setResidents]=useState<any[]>([]),[residentId,setResidentId]=useState(''),[meds,setMeds]=useState<any[]>([]),[records,setRecords]=useState<any[]>([]);
 const [month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}); const [edit,setEdit]=useState<MarEdit>(null); const [code,setCode]=useState('GIVEN'); const [notes,setNotes]=useState(''); const [saving,setSaving]=useState(false);
 useEffect(()=>{fetch('/api/residents').then(r=>r.json()).then(x=>setResidents(Array.isArray(x)?x:[]))},[]);
 useEffect(()=>{if(!residentId){setMeds([]);setRecords([]);return}Promise.all([fetch(`/api/medications?residentId=${residentId}`).then(r=>r.json()),fetch(`/api/medication-records?residentId=${residentId}&module=mar`).then(r=>r.json())]).then(([m,r])=>{setMeds(Array.isArray(m)?m.filter((x:any)=>x.active!==false):[]);setRecords(Array.isArray(r)?r:[])})},[residentId]);
 const resident=useMemo(()=>residents.find(r=>r.id===residentId),[residents,residentId]);
 const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(); const monthKey=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}`;
 const recordMap=useMemo(()=>{const map=new Map<string,any>();for(const r of records){const d=r.data||{};if(d.scheduledDate?.startsWith(monthKey))map.set(`${d.medicationId}|${d.scheduledDate}|${d.scheduledTime}`,r)}return map},[records,monthKey]);
 const signatureRows=useMemo(()=>{const seen=new Set<string>();return records.filter(r=>r.data?.scheduledDate?.startsWith(monthKey)).filter(r=>{const d=r.data||{};const k=`${d.staffName}|${d.staffInitials}|${d.administeredAt}`;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>String(a.data?.administeredAt||'').localeCompare(String(b.data?.administeredAt||'')))},[records,monthKey]);
 function prevMonth(){setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}function nextMonth(){setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}
 function timesFor(_:any){return ['08:00','14:00','17:00','20:00']}
 function dateFor(day:number){return `${monthKey}-${String(day).padStart(2,'0')}`}
 function openCell(m:any,day:number,time:string){const date=dateFor(day);const r=recordMap.get(`${m.id}|${date}|${time}`);setEdit({med:m,date,time,record:r});setCode(r?.data?.code||'GIVEN');setNotes(r?.data?.notes||'')}
 async function saveCell(){if(!edit)return;setSaving(true);const payload={residentId,module:'mar',title:'Medication Administration Record',status:'submitted',data:{medicationId:edit.med.id,medication:edit.med.name,dosage:edit.med.dosage,route:edit.med.route,frequency:edit.med.frequency,scheduledDate:edit.date,scheduledTime:edit.time,code,notes}};const url=edit.record?`/api/medication-records/${edit.record.id}`:'/api/medication-records';const r=await fetch(url,{method:edit.record?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){alert(j.error||'Unable to save MAR record.');return}setRecords(prev=>edit.record?prev.map(x=>x.id===j.id?j:x):[j,...prev]);setEdit(null)}
 return <>
 <div className="pagehead marNoPrint"><div><h2>Medication Administration Record</h2><div className="muted">Monthly MAR, scheduled dose times, staff initials, and administration status.</div></div><a className="btn btn-ghost" href="/medications">Back</a></div>
 <div className="card section marNoPrint"><div className="field"><label>Resident Name</label><select className="select" value={residentId} onChange={e=>setResidentId(e.target.value)}><option value="">Select Resident</option>{residents.map(r=><option key={r.id} value={r.id}>{r.firstName} {r.lastName}</option>)}</select></div></div>
 {resident&&<div className="marResidentGrid"><Info label="Resident Name" value={`${resident.firstName||''} ${resident.lastName||''}`}/><Info label="AHCCCS/MEMBER ID" value={resident.ahcccsId||'—'}/><Info label="DOB" value={fmtDate(resident.dob)}/><Info label="Diagnosis (specify if new or continuing)" value={resident.diagnosis||'—'} wide/><Info label="Admit Date" value={fmtDate(resident.admitDate)}/><Info label="Facility" value={resident.facility||'Shalom Behavioral House LLC'}/></div>}
 {residentId&&<><div className="marMonth"><button type="button" onClick={prevMonth}>‹</button><b>{month.toLocaleString('en-US',{month:'short',year:'numeric'})}</b><button type="button" onClick={nextMonth}>›</button></div>
 <div className="marBlocks">{meds.map(m=><div className="marMedication" key={m.id}><div className="marMedicationHead"><div><b>Medication Name:</b> {m.name} {m.dosage&&<span> · {m.dosage}</span>} &nbsp; <b>Instruction:</b> {m.instructions||m.frequency||'—'} &nbsp; <b>Other Instruction:</b> {m.otherInstructions||m.other_instructions||'N/A'}</div><div><b>Expiration Date:</b> {fmtDate(m.expirationDate||m.expiration_date)} &nbsp; <b>Prescriber Name:</b> {m.prescriber||'—'}</div><span className="marRefill">Refill Count <b>{m.refillCount??m.refill_count??0}</b></span></div>
 {timesFor(m).map((time:string)=><div className="marGridWrap" key={time}><table className="marGrid"><thead><tr><th>Time</th>{Array.from({length:days},(_,i)=><th key={i}>{i+1}</th>)}</tr></thead><tbody><tr><td className="marTime">{formatTime(time)}</td>{Array.from({length:days},(_,i)=>{const date=dateFor(i+1);const r=recordMap.get(`${m.id}|${date}|${time}`);const d=r?.data||{};return <td key={i} className={`marCell code-${String(d.code||'').toLowerCase()}`}><button disabled={!canAdminister} title={r?`${d.code||''} ${d.staffInitials||''}`:'Record administration'} onClick={()=>openCell(m,i+1,time)}><span>{d.code||''}</span><small>{d.staffInitials||''}</small></button></td>})}</tr></tbody></table></div>)}</div>)}{!meds.length&&<div className="card empty">No active medications found for this resident. Add medications and dose times under Resident Medication first.</div>}</div>
 <div className="marLegend"><div><b>H:</b> Hospital</div><div><b>HP:</b> Home Pass</div><div><b>RM:</b> Refused Med</div><div><b>HO:</b> On Hold per Provider’s Orders</div><div><b>UN:</b> Unavailable (documentation required)</div><div><b>D:</b> This medication is Discontinued</div></div>
 <div className="card tablewrap marStaff"><h3>Staff Name and Signature</h3><table className="table"><thead><tr><th>Staff Name and Signature</th><th>Title</th><th>Initials</th><th>Date / Time</th></tr></thead><tbody>{signatureRows.map(r=><tr key={r.id}><td>Digitally Signed by {r.data?.staffName||'Staff'}</td><td>{r.data?.staffRole||'—'}</td><td>{r.data?.staffInitials||'—'}</td><td>{r.data?.administeredAt?new Date(r.data.administeredAt).toLocaleString():'—'}</td></tr>)}</tbody></table>{!signatureRows.length&&<div className="empty">No MAR administrations recorded for this month.</div>}</div>
 <div className="marNoPrint" style={{marginTop:16}}><button className="btn btn-ghost" onClick={()=>window.print()}>Print Report</button></div></>}
 {edit&&<div className="modalOverlay marNoPrint"><div className="card section modalCard"><div className="pagehead"><div><h2>Record Administration</h2><div className="muted">{edit.med.name} · {formatTime(edit.time)} · {fmtDate(edit.date)}</div></div><button className="btn btn-ghost" onClick={()=>setEdit(null)}>Close</button></div><div className="formgrid"><div className="field"><label>Status Code</label><select className="select" value={code} onChange={e=>setCode(e.target.value)}>{CODES.map(c=><option key={c}>{c}</option>)}</select></div><div className="field full"><label>Notes / Documentation</label><textarea className="textarea" value={notes} onChange={e=>setNotes(e.target.value)}/></div></div><div className="actions" style={{justifyContent:'flex-end',marginTop:18}}><button className="btn btn-ghost" onClick={()=>setEdit(null)}>Cancel</button><button className="btn btn-primary" disabled={saving} onClick={saveCell}>{saving?'Saving...':'Record Administration'}</button></div></div></div>}
 </>
}
function Info({label,value,wide=false}:{label:string;value:any;wide?:boolean}){return <div className={`marInfo ${wide?'wide':''}`}><b>{label}:</b> <span>{value||'—'}</span></div>}
function formatTime(t:string){if(!t)return'—';const [hh,mm]=t.split(':').map(Number);if(!Number.isFinite(hh))return t;return `${hh%12||12}:${String(mm||0).padStart(2,'0')} ${hh>=12?'PM':'AM'}`}
function fmtDate(v:any){if(!v)return'—';const s=String(v).slice(0,10);const [y,m,d]=s.split('-');return y&&m&&d?`${m}/${d}/${y}`:String(v)}
