"use client";
import {useEffect,useMemo,useState} from "react";
import SignaturePad from "@/components/SignaturePad";

type Resident={id:string;firstName:string;lastName:string;referenceId?:string;ahcccsId?:string;dob?:string;admitDate?:string;diagnosis?:string};
type Field=[string,string,string];
const definitions:Record<string,{title:string;fields:Field[]}>= {
 "medication-reconciliation":{title:"Medication Reconciliation",fields:[["date","Date","date"],["allergies","Allergies and reactions","text"],["medication","Name of Medication","text"],["dose","Dose","text"],["route","Route","text"],["frequency","Frequency","text"],["startDate","Start Date","date"],["stopDate","Stop/Change Date","date"],["reason","Reason for Stop/Change","textarea"],["provider","Provider Name","text"],["signer","Signer","text"]]},
 "medication-count":{title:"Medication Count",fields:[["month","Month / Year","month"],["facilityAddress","Facility Address","text"],["medication","Medication Name","text"],["dose","Dose","text"],["instructions","Prescription Instructions","text"],["provider","Prescribing Provider","text"],["date","Date","date"],["shiftFrom","Shift From","time"],["shiftTo","Shift To","time"],["given","Number of tablets/capsules given","number"],["beginning","Beginning Medication Count","number"],["ending","Ending Medication Count","number"],["signer","Signer","text"]]},
 "informed-consent":{title:"Informed Consent for Medications",fields:[["adminDate","Admin Date","date"],["medication","Medication","text"],["startDate","Medication Start Date","date"],["dcDate","D/C Date","date"],["instructions","Instructions / Risks / Benefits discussed","textarea"],["residentSignature","Resident / Representative Signature","text"],["witness","Witness Name","text"],["witnessSignature","Witness Signature","text"],["signer","Signer","text"]]},
 "prn":{title:"PRN Medication Log",fields:[["medication","Medication and Strength","text"],["instructions","Instructions","text"],["prescriber","Prescriber Name","text"],["site","Site","text"],["date","Date","date"],["time","Time","time"],["quantity","Quantity","text"],["intensity","Intensity (0-10 if applicable)","number"],["reason","Reason","textarea"],["effectiveness","Effectiveness / Follow-up","textarea"],["signer","Signer","text"]]},
};
export default function MedicationManager({module,canManage=true}:{module:string;canManage?:boolean}){
 const def=definitions[module];const [residents,setResidents]=useState<Resident[]>([]);const [residentId,setResidentId]=useState("");const [rows,setRows]=useState<any[]>([]);const [form,setForm]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [editId,setEditId]=useState<string|null>(null);const selected=useMemo(()=>residents.find(r=>r.id===residentId),[residents,residentId]);
 useEffect(()=>{fetch('/api/residents').then(r=>r.json()).then(x=>setResidents(Array.isArray(x)?x:[]))},[]);
 async function load(id=residentId){if(!id){setRows([]);return}const r=await fetch(`/api/medication-records?residentId=${id}&module=${module}`);const x=await r.json();setRows(Array.isArray(x)?x:[])}
 useEffect(()=>{load(residentId)},[residentId,module]);
 if(!def)return <div className="card empty">Unknown medication module.</div>;
 async function save(status:string){if(!residentId){setMessage("Please select a resident.");return}const url=editId?`/api/medication-records/${editId}`:'/api/medication-records';const r=await fetch(url,{method:editId?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({residentId,module,title:def.title,status,data:form})});const x=await r.json();if(!r.ok){setMessage(x.error||'Unable to save');return}setMessage(editId?'Record updated.':status==='draft'?'Draft saved.':'Record submitted.');setForm({});setEditId(null);load()}
 async function del(id:string){if(!confirm('Delete this record?'))return;const r=await fetch(`/api/medication-records/${id}`,{method:'DELETE'});if(!r.ok){const j=await r.json();alert(j.error||'Unable to delete.');return}load()}
 function editRow(x:any){setEditId(x.id);setResidentId(x.resident_id);setForm(x.data||{});window.scrollTo({top:0,behavior:'smooth'})}
 return <><div className="pagehead"><div><h2>{def.title}</h2><div className="muted">Create, save, update and review resident medication records.</div></div><a className="btn btn-ghost" href="/medications">Back</a></div>
 <div className="card section"><div className="field"><label>Resident Name</label><select className="select" value={residentId} onChange={e=>setResidentId(e.target.value)}><option value="">Select Resident</option>{residents.map(r=><option key={r.id} value={r.id}>{r.firstName} {r.lastName}</option>)}</select></div>{selected&&<div className="grid grid3" style={{marginTop:16}}><div><small className="muted">AHCCCS / MEMBER ID</small><div><b>{selected.ahcccsId||selected.referenceId||'—'}</b></div></div><div><small className="muted">DOB</small><div><b>{selected.dob||'—'}</b></div></div><div><small className="muted">Admit Date</small><div><b>{selected.admitDate||'—'}</b></div></div></div>}</div>
 {canManage&&<div className="card section"><div className="pagehead"><div><h3>{editId?'Edit Record':'New Record'}</h3></div>{editId&&<button className="btn btn-ghost" onClick={()=>{setEditId(null);setForm({})}}>Cancel Edit</button>}</div><div className="formgrid">{def.fields.map(([name,label,type])=>{const sig=label.toLowerCase().includes('signature')||name.toLowerCase().includes('signature');return <div className={`field ${sig?'full':''}`} key={name}>{sig?<SignaturePad label={label} value={form[name]||''} onChange={v=>setForm({...form,[name]:v})}/>:<><label>{label}</label>{type==='textarea'?<textarea className="textarea" value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})}/>:<input className="input" type={type} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})}/>}</>}</div>})}</div>{message&&<div className="muted" style={{marginTop:12}}>{message}</div>}<div className="actions" style={{justifyContent:'flex-end',marginTop:18}}><button className="btn btn-ghost" onClick={()=>save('draft')}>{editId?'Update Draft':'Save Draft'}</button><button className="btn btn-primary" onClick={()=>save('submitted')}>{editId?'UPDATE':'Submit'}</button></div></div>}
 <div className="card tablewrap"><table className="table"><thead><tr><th>Created</th><th>Status</th><th>Medication / Date</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td><span className="badge blue">{x.status}</span></td><td>{x.data?.medication||x.data?.date||def.title}</td><td>{canManage?<div className="actions"><button className="btn btn-ghost compactBtn" onClick={()=>editRow(x)}>Edit</button><button className="btn btn-danger compactBtn" onClick={()=>del(x.id)}>Delete</button></div>:<span className="muted">View only</span>}</td></tr>)}</tbody></table>{residentId&&!rows.length&&<div className="empty">No records found.</div>}</div></>
}
