"use client";
import {useEffect,useMemo,useState} from "react";

type Resident={id:string;firstName:string;lastName:string;referenceId?:string;ahcccsId?:string;dob?:string;admitDate?:string;diagnosis?:string};
type Field=[string,string,string];
const definitions:Record<string,{title:string;fields:Field[]}>={
 "medication-reconciliation":{title:"Medication Reconciliation",fields:[["date","Date","date"],["allergies","Allergies and reactions","text"],["medication","Name of Medication","text"],["dose","Dose","text"],["route","Route","text"],["frequency","Frequency","text"],["startDate","Start Date","date"],["stopDate","Stop/Change Date","date"],["reason","Reason for Stop/Change","textarea"],["provider","Provider Name","text"],["signer","Signer","text"]]},
 "medication-count":{title:"Medication Count",fields:[["month","Month / Year","month"],["facilityAddress","Facility Address","text"],["medication","Medication Name","text"],["dose","Dose","text"],["instructions","Prescription Instructions","text"],["provider","Prescribing Provider","text"],["date","Date","date"],["shiftFrom","Shift From","time"],["shiftTo","Shift To","time"],["given","Number of tablets/capsules given","number"],["beginning","Beginning Medication Count","number"],["ending","Ending Medication Count","number"],["signer","Signer","text"]]},
 "informed-consent":{title:"Informed Consent for Medications",fields:[["adminDate","Admin Date","date"],["medication","Medication","text"],["startDate","Medication Start Date","date"],["dcDate","D/C Date","date"],["instructions","Instructions / Risks / Benefits discussed","textarea"],["residentSignature","Resident / Representative Signature","text"],["witness","Witness Name","text"],["witnessSignature","Witness Signature","text"],["signer","Signer","text"]]},
 "prn":{title:"PRN Medication Log",fields:[["medication","Medication and Strength","text"],["instructions","Instructions","text"],["prescriber","Prescriber Name","text"],["site","Site","text"],["date","Date","date"],["time","Time","time"],["quantity","Quantity","text"],["intensity","Intensity (0-10 if applicable)","number"],["reason","Reason","textarea"],["effectiveness","Effectiveness / Follow-up","textarea"],["signer","Signer","text"]]},
};
export default function MedicationManager({module}:{module:string}){const def=definitions[module];const [residents,setResidents]=useState<Resident[]>([]);const [residentId,setResidentId]=useState("");const [rows,setRows]=useState<any[]>([]);const [form,setForm]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const selected=useMemo(()=>residents.find(r=>r.id===residentId),[residents,residentId]);
 useEffect(()=>{fetch('/api/residents').then(r=>r.json()).then(x=>setResidents(Array.isArray(x)?x:[]))},[]);
 async function load(id=residentId){if(!id){setRows([]);return}const r=await fetch(`/api/medication-records?residentId=${id}&module=${module}`);const x=await r.json();setRows(Array.isArray(x)?x:[])}
 useEffect(()=>{load(residentId)},[residentId,module]);
 if(!def)return <div className="card empty">Unknown medication module.</div>;
 async function save(status:string){if(!residentId){setMessage("Please select a resident.");return}const r=await fetch('/api/medication-records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({residentId,module,title:def.title,status,data:form})});const x=await r.json();if(!r.ok){setMessage(x.error||'Unable to save');return}setMessage(status==='draft'?'Draft saved.':'Record submitted.');setForm({});load()}
 async function del(id:string){if(!confirm('Delete this record?'))return;await fetch(`/api/medication-records/${id}`,{method:'DELETE'});load()}
 return <><div className="pagehead"><div><h2>{def.title}</h2><div className="muted">Create, save and review resident medication records.</div></div><a className="btn btn-ghost" href="/medications">Back</a></div><div className="card section"><div className="field"><label>Resident Name</label><select className="select" value={residentId} onChange={e=>setResidentId(e.target.value)}><option value="">Select Resident</option>{residents.map(r=><option key={r.id} value={r.id}>{r.firstName} {r.lastName}</option>)}</select></div>{selected&&<div className="grid grid3" style={{marginTop:16}}><div><small className="muted">AHCCCS / MEMBER ID</small><div><b>{selected.ahcccsId||selected.referenceId||'—'}</b></div></div><div><small className="muted">DOB</small><div><b>{selected.dob||'—'}</b></div></div><div><small className="muted">Admit Date</small><div><b>{selected.admitDate||'—'}</b></div></div></div>}</div><div className="card section"><div className="formgrid">{def.fields.map(([name,label,type])=><div className="field" key={name}><label>{label}</label>{type==='textarea'?<textarea className="textarea" value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})}/>:<input className="input" type={type} value={form[name]||''} onChange={e=>setForm({...form,[name]:e.target.value})}/>}</div>)}</div>{message&&<div className="muted" style={{marginTop:12}}>{message}</div>}<div style={{display:'flex',gap:10,justifyContent:'flex-end',marginTop:18}}><button className="btn btn-ghost" onClick={()=>save('draft')}>Save Draft</button><button className="btn btn-primary" onClick={()=>save('submitted')}>Submit</button></div></div><div className="card tablewrap"><table className="table"><thead><tr><th>Created</th><th>Status</th><th>Medication / Date</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString()}</td><td><span className="badge blue">{x.status}</span></td><td>{x.data?.medication||x.data?.date||def.title}</td><td><button className="btn btn-danger" style={{padding:'7px 9px'}} onClick={()=>del(x.id)}>Delete</button></td></tr>)}</tbody></table>{residentId&&!rows.length&&<div className="empty">No records found.</div>}</div></>}
