"use client";
import {useEffect,useState} from "react";
const blank={name:'',dosage:'',route:'',frequency:'',prescriber:'',startDate:'',endDate:'',instructions:'',active:true};
export default function ResidentMedicationManager({canManage=true}:{canManage?:boolean}){const [residents,setResidents]=useState<any[]>([]),[residentId,setResidentId]=useState(''),[rows,setRows]=useState<any[]>([]),[form,setForm]=useState<any>(blank),[editId,setEditId]=useState<string|null>(null);
 useEffect(()=>{fetch('/api/residents').then(r=>r.json()).then(x=>setResidents(Array.isArray(x)?x:[]));load()},[]);async function load(){const r=await fetch('/api/medications');const x=await r.json();setRows(Array.isArray(x)?x:[])}
 async function save(e:any){e.preventDefault();if(!residentId)return;const r=await fetch(editId?`/api/medications/${editId}`:'/api/medications',{method:editId?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,residentId})});const j=await r.json().catch(()=>({}));if(!r.ok){alert(j.error||'Unable to save medication.');return}setForm(blank);setEditId(null);setResidentId('');load()}
 async function del(id:string){if(!confirm('Delete medication?'))return;const r=await fetch(`/api/medications/${id}`,{method:'DELETE'});if(!r.ok){const j=await r.json();alert(j.error||'Unable to delete medication.');return}load()}
 function edit(m:any){setEditId(m.id);setResidentId(m.residentId||m.resident_id);setForm({name:m.name||'',dosage:m.dosage||'',route:m.route||'',frequency:m.frequency||'',prescriber:m.prescriber||'',startDate:m.startDate||m.start_date||'',endDate:m.endDate||m.end_date||'',instructions:m.instructions||'',active:m.active!==false});window.scrollTo({top:0,behavior:'smooth'})}
 return <><div className="pagehead"><div><h2>Resident Medication</h2><div className="muted">Maintain the active medication list for each resident.</div></div><a className="btn btn-ghost" href="/medications">Back</a></div>{canManage&&<form className="card section" onSubmit={save}><div className="pagehead"><h3>{editId?'Edit Medication':'Add Medication'}</h3>{editId&&<button type="button" className="btn btn-ghost" onClick={()=>{setEditId(null);setResidentId('');setForm(blank)}}>Cancel Edit</button>}</div><div className="formgrid"><div className="field"><label>Resident</label><select className="select" required value={residentId} onChange={e=>setResidentId(e.target.value)}><option value="">Select Resident</option>{residents.map(r=><option key={r.id} value={r.id}>{r.firstName} {r.lastName}</option>)}</select></div>{[['name','Medication Name','text'],['dosage','Dosage / Strength','text'],['route','Route','text'],['frequency','Frequency','text'],['prescriber','Prescribing Provider','text'],['startDate','Start Date','date'],['endDate','End Date','date']].map(([n,l,t])=><div className="field" key={n}><label>{l}</label><input className="input" type={t} value={form[n]||''} onChange={e=>setForm({...form,[n]:e.target.value})}/></div>)}</div><div className="field" style={{marginTop:12}}><label>Instructions</label><textarea className="textarea" value={form.instructions||''} onChange={e=>setForm({...form,instructions:e.target.value})}/></div><label className="checkrow" style={{marginTop:12}}><input type="checkbox" checked={form.active!==false} onChange={e=>setForm({...form,active:e.target.checked})}/> Active medication</label><div style={{textAlign:'right',marginTop:18}}><button className="btn btn-primary">{editId?'Update Medication':'Add Medication'}</button></div></form>}<div className="card tablewrap"><table className="table"><thead><tr><th>Resident</th><th>Medication</th><th>Dose</th><th>Route</th><th>Frequency</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td>{m.residentName||'—'}</td><td>{m.name}</td><td>{m.dosage||'—'}</td><td>{m.route||'—'}</td><td>{m.frequency||'—'}</td><td><span className={`badge ${m.active?'green':'gray'}`}>{m.active?'Active':'Inactive'}</span></td><td>{canManage?<div className="actions"><button className="btn btn-ghost compactBtn" onClick={()=>edit(m)}>Edit</button><button className="btn btn-danger compactBtn" onClick={()=>del(m.id)}>Delete</button></div>:<span className="muted">View only</span>}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No medications added yet.</div>}</div></>}
