"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
export default function ResidentManager({canCreate,canEdit,canDelete,canBook,initialSearch=""}:{canCreate:boolean;canEdit:boolean;canDelete:boolean;canBook:boolean;initialSearch?:string}){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(initialSearch),[open,setOpen]=useState(false),[edit,setEdit]=useState<any>(null);
 async function load(){const r=await fetch('/api/residents');const j=await r.json();setRows(Array.isArray(j)?j:[])}useEffect(()=>{load()},[]);
 async function save(e:any){e.preventDefault();const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());const url=edit?`/api/residents/${edit.id}`:'/api/residents';const r=await fetch(url,{method:edit?'PUT':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok){alert(j.error||'Unable to save resident.');return}setOpen(false);setEdit(null);load()}
 async function del(id:string){if(!confirm('Delete resident and all related records?'))return;const r=await fetch(`/api/residents/${id}`,{method:'DELETE'});const j=await r.json().catch(()=>({}));if(!r.ok){alert(j.error||'Unable to delete resident.');return}load()}
 const filtered=rows.filter(r=>`${r.firstName} ${r.lastName} ${r.referenceId}`.toLowerCase().includes(q.toLowerCase()));
 return <><div className="pagehead"><div><h2>All Residents</h2><div className="muted">Resident census, profiles and appointment access.</div></div>{canCreate&&<button className="btn btn-primary" onClick={()=>{setEdit(null);setOpen(true)}}>+ Add Resident</button>}</div>
 <div className="card section"><div className="toolbar"><input className="input" style={{minWidth:300}} placeholder="Search by name or reference ID" value={q} onChange={e=>setQ(e.target.value)}/><span className="muted">{filtered.length} residents</span></div></div>
 <div className="card tablewrap"><table className="table"><thead><tr><th>Resident Name</th><th>Reference ID</th><th>Phone</th><th>Email</th><th>Status</th><th>Appointment</th><th>Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><b>{r.firstName} {r.lastName}</b></td><td>{r.referenceId}</td><td>{r.phone||'—'}</td><td>{r.email||'—'}</td><td><span className={`badge ${(r.status||'').toLowerCase()==='active'?'green':'gray'}`}>{r.status}</span></td><td>{canBook?<Link className="btn btn-soft compactBtn" href={`/appointments?residentId=${r.id}`}>Book Appointment</Link>:<span className="muted">View only</span>}</td><td><div className="actions">{canEdit&&<button className="btn btn-ghost compactBtn" onClick={()=>{setEdit(r);setOpen(true)}}>Edit</button>}{canDelete&&<button className="btn btn-danger compactBtn" onClick={()=>del(r.id)}>Delete</button>}</div></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No residents found.</div>}</div>
 {open&&<div className="modalOverlay"><form className="card section modalCard" onSubmit={save}><div className="pagehead"><div><h2>{edit?'Edit Resident':'Add Resident'}</h2><div className="muted">Resident demographics and admission details.</div></div><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Close</button></div><div className="formgrid">{[['firstName','First Name'],['lastName','Last Name'],['referenceId','Reference ID'],['ahcccsId','AHCCCS / Member ID'],['phone','Phone'],['email','Email'],['diagnosis','Diagnosis'],['facility','Facility'],['status','Status']].map(([n,l])=><div className="field" key={n}><label>{l}</label><input className="input" name={n} defaultValue={edit?.[n]||''} required={['firstName','lastName','referenceId'].includes(n)}/></div>)}<div className="field"><label>Date of Birth</label><input className="input" type="date" name="dob" defaultValue={edit?.dob?.slice(0,10)||''}/></div><div className="field"><label>Admit Date</label><input className="input" type="date" name="admitDate" defaultValue={edit?.admitDate?.slice(0,10)||''}/></div></div><div className="actions" style={{justifyContent:'flex-end',marginTop:18}}><button type="button" className="btn btn-ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn-primary">{edit?'Update Resident':'Save Resident'}</button></div></form></div>}</>
}
