export type Field={key:string;label:string;type?:"text"|"date"|"time"|"number"|"textarea"|"select"|"checkbox"|"file";options?:string[];required?:boolean;placeholder?:string};
export type EmployeeModule={slug:string;title:string;description:string;fields:Field[]};
export const employeeModules:EmployeeModule[]=[
{slug:"personal-information",title:"Personal Information",description:"Employee identity, contact, driver and emergency details.",fields:[
{key:"date",label:"Date",type:"date"},{key:"first_name",label:"First Name",required:true},{key:"last_name",label:"Last Name",required:true},{key:"mi",label:"MI"},{key:"street",label:"Street"},{key:"city",label:"City"},{key:"state",label:"State"},{key:"zip",label:"Zip"},{key:"ssn",label:"Soc Sec No"},{key:"birth_date",label:"Birth Date",type:"date"},{key:"telephone",label:"Telephone"},{key:"personal_cell",label:"Personal Cell"},{key:"work_phone",label:"Work"},{key:"business_cell",label:"Business Cell"},{key:"drivers_license",label:"Driver’s License"},{key:"license_state",label:"State of Issue"},{key:"license_number",label:"License No"},{key:"license_expiration",label:"Expiration Date",type:"date"},{key:"business_email",label:"Business Email"},{key:"personal_email",label:"Personal Email"},{key:"emergency_name",label:"Emergency Contact Name"},{key:"emergency_relationship",label:"Relationship"},{key:"emergency_phone",label:"Emergency Contact Phone"}]},
{slug:"offer-letter",title:"Offer Letter",description:"Create and retain employee offer letter records.",fields:[{key:"employee_name",label:"Employee Name",required:true},{key:"position",label:"Position"},{key:"start_date",label:"Start Date",type:"date"},{key:"pay_rate",label:"Pay Rate"},{key:"employment_type",label:"Employment Type",type:"select",options:["Full Time","Part Time","Contractor","PRN"]},{key:"offer_details",label:"Offer Details",type:"textarea"},{key:"employee_signature",label:"Employee Signature"},{key:"authorized_signature",label:"Authorized Signature"}]},
{slug:"tb-risk-assessment",title:"TB Risk Assessment",description:"Tuberculosis screening and risk assessment for newly hired staff.",fields:[{key:"employee_name",label:"Employee Name",required:true},{key:"date",label:"Date",type:"date"},{key:"foreign_country",label:"Spent more than 30 days in a country with an elevated TB rate?",type:"select",options:["Yes","No"]},{key:"tb_contact",label:"Close contact with anyone who had active TB since last TB test?",type:"select",options:["Yes","No"]},{key:"symptoms",label:"Current TB symptoms / details",type:"textarea"},{key:"tb_treated",label:"Treated with medication for TB?",type:"select",options:["Yes","No"]},{key:"latent_tb",label:"Diagnosed with latent TB infection / positive TB test?",type:"select",options:["Yes","No"]},{key:"active_tb",label:"Diagnosed with active TB disease?",type:"select",options:["Yes","No"]},{key:"immune_compromised",label:"Compromised immune system / risk condition?",type:"select",options:["Yes","No"]},{key:"employee_signature",label:"Employee Signature"},{key:"signers",label:"Signers"}]},
{slug:"forms-2023",title:"Forms 2023",description:"Arizona withholding form upload and tracking.",fields:[{key:"document",label:"Choose File",type:"file"},{key:"type",label:"Type"},{key:"notes",label:"Notes",type:"textarea"}]},
{slug:"lrc-1031a",title:"LRC-1031A",description:"LRC employment document upload and tracking.",fields:[{key:"document",label:"Choose File",type:"file"},{key:"type",label:"Type"},{key:"notes",label:"Notes",type:"textarea"}]},
{slug:"job-description",title:"Job Description",description:"Employee job description and acknowledgement.",fields:[{key:"employee_name",label:"Employee Name",required:true},{key:"job_title",label:"Job Title"},{key:"facility",label:"Facility"},{key:"description",label:"Job Description",type:"textarea"},{key:"employee_signature",label:"Employee Signature"},{key:"supervisor_signature",label:"Supervisor Signature"}]},
{slug:"fw4",title:"FW4",description:"Federal W-4 document upload and tracking.",fields:[{key:"document",label:"Choose File",type:"file"},{key:"type",label:"Type"},{key:"notes",label:"Notes",type:"textarea"}]},
{slug:"aps-consent",title:"APS Consent",description:"Consent for APS registry search.",fields:[{key:"employee_name",label:"Employee Name",required:true},{key:"date",label:"Date",type:"date"},{key:"consent",label:"Employee consents to APS registry search",type:"checkbox"},{key:"employee_signature",label:"Employee Signature"},{key:"signers",label:"Signers"}]},
{slug:"fw9",title:"FW9",description:"Federal W-9 document upload and tracking.",fields:[{key:"document",label:"Choose File",type:"file"},{key:"type",label:"Type"},{key:"notes",label:"Notes",type:"textarea"}]},
{slug:"i-9",title:"I-9",description:"USCIS I-9 document upload and tracking.",fields:[{key:"document",label:"Choose File",type:"file"},{key:"type",label:"Type"},{key:"notes",label:"Notes",type:"textarea"}]},
{slug:"employee-termination",title:"Employee Termination",description:"Termination and rehire eligibility record.",fields:[{key:"employee_name",label:"Name of Terminated Employee",required:true},{key:"date",label:"Date",type:"date"},{key:"hire_date",label:"Hire Date",type:"date"},{key:"termination_date",label:"Termination Date",type:"date"},{key:"reason",label:"Reason for Termination",type:"textarea"},{key:"termination_type",label:"Termination Type",type:"select",options:["Voluntary","Involuntary"]},{key:"disciplinary_actions",label:"Disciplinary Actions Prior to Termination",type:"textarea"},{key:"copy_provided",label:"Copy Provided to Employee",type:"select",options:["Yes","No"]},{key:"eligible_rehire",label:"Eligible for Rehire",type:"select",options:["Yes","No"]},{key:"supervisor_signature",label:"Supervisor Signature"}]},
{slug:"all-employee-forms",title:"All Employee Forms",description:"Central employee document register.",fields:[{key:"document_name",label:"Document Name",required:true},{key:"document_date",label:"Date",type:"date"},{key:"document",label:"Document",type:"file"},{key:"notes",label:"Notes",type:"textarea"}]},
{slug:"time-off-request",title:"Time Off Request",description:"Employee leave and time-off request.",fields:[{key:"employee_name",label:"Employee Name",required:true},{key:"request_type",label:"Request Type",type:"select",options:["Vacation","Sick","Personal","Unpaid","Other"]},{key:"start_date",label:"Start Date",type:"date",required:true},{key:"end_date",label:"End Date",type:"date",required:true},{key:"hours",label:"Total Hours",type:"number"},{key:"reason",label:"Reason",type:"textarea"},{key:"employee_signature",label:"Employee Signature"},{key:"manager_status",label:"Manager Decision",type:"select",options:["Pending","Approved","Rejected"]},{key:"manager_notes",label:"Manager Notes",type:"textarea"}]},
{slug:"time-sheet",title:"Time Sheet",description:"Employee hours, overtime, holiday and signature.",fields:[{key:"employee_name",label:"Employee Name",required:true},{key:"facility",label:"Facility"},{key:"period_start",label:"Period Start",type:"date"},{key:"period_end",label:"Period End",type:"date"},{key:"regular_hours",label:"Reg. Hours",type:"number"},{key:"ot_hours",label:"O.T Hours",type:"number"},{key:"holiday_hours",label:"Holiday",type:"number"},{key:"total_hours",label:"Total",type:"number"},{key:"employee_signature",label:"Employee Signature"},{key:"office_notes",label:"Office Use Only",type:"textarea"}]},
{slug:"bht-schedule",title:"BHT Schedule",description:"Monthly BHT facility schedule.",fields:[{key:"facility",label:"Facility",required:true},{key:"month",label:"Month / Year"},{key:"employee_name",label:"BHT Employee"},{key:"shift_date",label:"Shift Date",type:"date"},{key:"start_time",label:"Start Time",type:"time"},{key:"end_time",label:"End Time",type:"time"},{key:"notes",label:"Notes",type:"textarea"}]},
{slug:"employee-performance",title:"Employee Performance",description:"Employee performance review and evaluation.",fields:[{key:"employee_name",label:"Employee Name",required:true},{key:"review_date",label:"Review Date",type:"date"},{key:"reviewer",label:"Reviewer"},{key:"period",label:"Review Period"},{key:"attendance",label:"Attendance",type:"select",options:["Excellent","Good","Satisfactory","Needs Improvement","Unsatisfactory"]},{key:"quality",label:"Quality of Work",type:"select",options:["Excellent","Good","Satisfactory","Needs Improvement","Unsatisfactory"]},{key:"communication",label:"Communication",type:"select",options:["Excellent","Good","Satisfactory","Needs Improvement","Unsatisfactory"]},{key:"teamwork",label:"Teamwork",type:"select",options:["Excellent","Good","Satisfactory","Needs Improvement","Unsatisfactory"]},{key:"strengths",label:"Strengths",type:"textarea"},{key:"improvements",label:"Areas for Improvement",type:"textarea"},{key:"goals",label:"Goals / Action Plan",type:"textarea"},{key:"employee_signature",label:"Employee Signature"},{key:"reviewer_signature",label:"Reviewer Signature"}]},
{slug:"employee-tracking",title:"Employee Tracking / Upload",description:"Track employee compliance files and due dates.",fields:[{key:"file_name",label:"File Name",required:true},{key:"document",label:"Choose File",type:"file"},{key:"due_date",label:"Due Date",type:"date"},{key:"notes",label:"Notes",type:"textarea"}]},
];
export const trainingModules:EmployeeModule[]=[
["tuberculosis-training","Tuberculosis Training"],["self-administration-medication","Assistance with Self-Administration of Medication"],["fall-prevention","Fall Prevention and Recovery Training"],["infection-control","Infection Control"],["facility-orientation","On Site and Facility Orientation Verification"],["skills-knowledge","Skills and Knowledge Training"]
].map(([slug,title])=>({slug,title,description:"Employee training completion and acknowledgement.",fields:[{key:"employee_name",label:"Employee Name",required:true},{key:"position",label:"Position"},{key:"date",label:"Date",type:"date"},{key:"topic_covered",label:"Topic Covered",type:"textarea"},{key:"teaching_method",label:"Teaching Method"},{key:"hours",label:"Training Hours",type:"number"},{key:"trainer",label:"Trainer / Instructor"},{key:"employee_signature",label:"Employee Signature"},{key:"signers",label:"Signers"}]}));
export const allEmployeeModules=[...employeeModules,...trainingModules];
export function getEmployeeModule(slug:string){return allEmployeeModules.find(m=>m.slug===slug)}
